### PR TITLE
Fixed install, added both PIC & static targets

### PR DESCRIPTION
**Pull request by tjanc**
- Added PIC target
- Added static target
- Fixed install: generated `SundownApiaryConfigVersion.cmake` ends up in `CMAKE_CURRENT_BINARY_DIR`.
- naming

### CODE REVIEW

**Comment by kylef** [comment]
Is this needed? The caller could set https://cmake.org/cmake/help/v3.4/variable/CMAKE_POSITION_INDEPENDENT_CODE.html on the library if they want PIC?

**Comment by tjanc** [comment]
@kylef I explored this a little and finally decided for PIC targets anyway. The global cmake variable you are referring to is just that: global. Currently, we need to build dependencies both as PIC _and_ non-PIC (think `libdrafter.so` and `drafter`). If you have a working example that avoids the PIC targets, I would be more than happy to drop them.

**Comment by klokane** [comment]
I dont know how it is usual in "cmake world", but what about `distclean` target

**Comment by tjanc** [comment]
@klokane in the cmake world, distclean is equivalent to deleting the build directory.
```
mkdir build
cd build
cmake ..
make
...
...
...
cd ..
rm -rf build
```

**Comment by klokane** [comment]
@tjanc all "subpackages" are hold in this tree?

**Pull request merged**
